CREATE TABLE IF NOT EXISTS scola_accounts(id text PRIMARY KEY, login text UNIQUE NOT NULL, password text NOT NULL, created timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS scola_sessions(token text PRIMARY KEY, owner text NOT NULL REFERENCES scola_accounts(id), expires timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS scola_sessions_owner ON scola_sessions(owner);
CREATE TABLE IF NOT EXISTS scola_settings(owner text PRIMARY KEY REFERENCES scola_accounts(id),name text NOT NULL,phone text NOT NULL DEFAULT '',address text NOT NULL DEFAULT '',year text NOT NULL);
CREATE TABLE IF NOT EXISTS scola_students(id text PRIMARY KEY,owner text NOT NULL REFERENCES scola_accounts(id),name text NOT NULL,class_name text NOT NULL,parent text NOT NULL,phone text NOT NULL,year text NOT NULL,fee integer NOT NULL CHECK(fee>0),schedule text NOT NULL,created text NOT NULL);
CREATE INDEX IF NOT EXISTS scola_students_owner ON scola_students(owner);
CREATE TABLE IF NOT EXISTS scola_payments(id text PRIMARY KEY,owner text NOT NULL REFERENCES scola_accounts(id),student_id text NOT NULL REFERENCES scola_students(id),amount integer NOT NULL CHECK(amount>0),method text NOT NULL,reference text NOT NULL,date text NOT NULL,created text NOT NULL,cancel_reason text);
CREATE INDEX IF NOT EXISTS scola_payments_owner_student ON scola_payments(owner,student_id);
CREATE TABLE IF NOT EXISTS scola_reminders(id text PRIMARY KEY,owner text NOT NULL REFERENCES scola_accounts(id),student_id text NOT NULL REFERENCES scola_students(id),created text NOT NULL);
CREATE INDEX IF NOT EXISTS scola_reminders_owner ON scola_reminders(owner);
ALTER TABLE scola_accounts ADD COLUMN IF NOT EXISTS school_owner text REFERENCES scola_accounts(id);
ALTER TABLE scola_accounts ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'director';
ALTER TABLE scola_accounts ADD COLUMN IF NOT EXISTS display_name text NOT NULL DEFAULT '';
ALTER TABLE scola_accounts ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;
ALTER TABLE scola_settings ADD COLUMN IF NOT EXISTS next_receipt integer NOT NULL DEFAULT 1;
ALTER TABLE scola_settings ADD COLUMN IF NOT EXISTS reminders_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE scola_settings ADD COLUMN IF NOT EXISTS receipts_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE scola_students ADD COLUMN IF NOT EXISTS consent boolean NOT NULL DEFAULT false;
ALTER TABLE scola_students ADD COLUMN IF NOT EXISTS consent_at text NOT NULL DEFAULT '';
ALTER TABLE scola_students ADD COLUMN IF NOT EXISTS external_ref text NOT NULL DEFAULT '';
ALTER TABLE scola_payments ADD COLUMN IF NOT EXISTS receipt_number integer;
ALTER TABLE scola_payments ADD COLUMN IF NOT EXISTS created_by text NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS scola_receipt_number ON scola_payments(owner,receipt_number);
CREATE TABLE IF NOT EXISTS scola_audit(id text PRIMARY KEY,owner text NOT NULL REFERENCES scola_accounts(id),actor text NOT NULL,event text NOT NULL,target text NOT NULL,detail text NOT NULL,created text NOT NULL);
CREATE INDEX IF NOT EXISTS scola_audit_owner ON scola_audit(owner,created);
CREATE TABLE IF NOT EXISTS scola_closings(id text PRIMARY KEY,owner text NOT NULL REFERENCES scola_accounts(id),day text NOT NULL,expected integer NOT NULL,counted integer NOT NULL,note text NOT NULL,actor text NOT NULL,closed boolean NOT NULL DEFAULT true,created text NOT NULL,UNIQUE(owner,day));
CREATE TABLE IF NOT EXISTS scola_snapshots(id text PRIMARY KEY,owner text NOT NULL REFERENCES scola_accounts(id),day text NOT NULL,payload text NOT NULL,created text NOT NULL,UNIQUE(owner,day));
CREATE TABLE IF NOT EXISTS scola_messages(id text PRIMARY KEY,owner text NOT NULL REFERENCES scola_accounts(id),student_id text NOT NULL REFERENCES scola_students(id),kind text NOT NULL,payment_id text,dedupe text UNIQUE NOT NULL,status text NOT NULL DEFAULT 'pending',provider_id text NOT NULL DEFAULT '',error text NOT NULL DEFAULT '',created text NOT NULL,updated text NOT NULL);
CREATE INDEX IF NOT EXISTS scola_messages_owner ON scola_messages(owner,created);
