import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {randomBytes,randomUUID} from 'node:crypto';
import pg from 'pg';
import {hashPassword,checkPassword,hashToken,validDate,validSchedule} from './security.mjs';
const production=process.env.NODE_ENV==='production';
if(!process.env.DATABASE_URL){console.error('DATABASE_URL is required. Configure PostgreSQL before starting.');process.exit(1);}
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:10,connectionTimeoutMillis:10000});
await pool.query(await readFile(new URL('./schema.sql',import.meta.url),'utf8'));
const staticRoot=resolve('dist');
const attempts=new Map();
const text=(v,max=120)=>typeof v==='string'?v.trim().slice(0,max):'';
const reply=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
function cookie(token,maxAge){return `scola_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${production?'; Secure':''}`;}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>32768)throw Object.assign(Error('Formulaire trop volumineux.'),{status:413});}try{return JSON.parse(raw);}catch{throw Object.assign(Error('Formulaire invalide.'),{status:400});}}
async function user(req){const token=/(?:^|;\s*)scola_session=([a-f0-9]{64})(?:;|$)/.exec(req.headers.cookie||'')?.[1];if(!token)return null;const r=await pool.query('SELECT owner FROM scola_sessions WHERE token=$1 AND expires>now()',[hashToken(token)]);return r.rows[0]?.owner||null;}
function csrf(req){if(!production&&!req.headers.origin)return true;try{return new URL(req.headers.origin).host===req.headers.host;}catch{return false;}}
async function signIn(res,owner){const token=randomBytes(32).toString('hex');await pool.query('INSERT INTO scola_sessions(token,owner,expires) VALUES($1,$2,now()+interval \'7 days\')',[hashToken(token),owner]);res.setHeader('Set-Cookie',cookie(token,604800));reply(res,200,{ok:true});}
const fallbackHash=await hashPassword(randomBytes(32).toString('hex'));
async function api(req,res,url){if(req.method==='POST'&&!csrf(req))return reply(res,403,{error:'Requête refusée.'});
if(url.pathname==='/api/auth/login'||url.pathname==='/api/auth/register'){if(req.method!=='POST')return reply(res,405,{error:'Méthode non autorisée.'});const b=await body(req),login=text(b.login,60).toLowerCase(),password=typeof b.password==='string'?b.password:'';const ip=(req.headers['x-forwarded-for']||req.socket.remoteAddress||'').toString().split(',').at(-1).trim();const now=Date.now();for(const [k,v]of attempts)if(v.until<now)attempts.delete(k);const keys=['ip:'+ip,'login:'+login];if(keys.some(k=>(attempts.get(k)?.count||0)>=12))return reply(res,429,{error:'Trop de tentatives. Réessayez dans 15 minutes.'});for(const k of keys){const old=attempts.get(k);attempts.set(k,{count:(old?.count||0)+1,until:old?.until||now+900000});}if(attempts.size>10000)attempts.delete(attempts.keys().next().value);
if(!/^[a-z0-9._-]{4,60}$/.test(login)||password.length<1||password.length>128)return reply(res,400,{error:'Vérifiez votre identifiant et votre mot de passe.'});
if(url.pathname.endsWith('register')){const school=text(b.school);if(!school||password.length<10)return reply(res,400,{error:'Indiquez l’école et un mot de passe de 10 caractères minimum.'});const client=await pool.connect();try{await client.query('BEGIN');const id=randomUUID();await client.query('INSERT INTO scola_accounts(id,login,password) VALUES($1,$2,$3)',[id,login,await hashPassword(password)]);await client.query('INSERT INTO scola_settings(owner,name,year) VALUES($1,$2,$3)',[id,school,'2026–2027']);await client.query('COMMIT');return await signIn(res,id);}catch(e){await client.query('ROLLBACK');if(e.code==='23505')return reply(res,409,{error:'Cet identifiant est déjà utilisé. Choisissez-en un autre.'});throw e;}finally{client.release();}}
const r=await pool.query('SELECT id,password FROM scola_accounts WHERE login=$1',[login]);const ok=await checkPassword(password,r.rows[0]?.password||fallbackHash);if(!ok||!r.rows[0])return reply(res,401,{error:'Identifiant ou mot de passe incorrect.'});attempts.delete('login:'+login);return signIn(res,r.rows[0].id);}
const owner=await user(req);if(!owner)return reply(res,401,{error:'Votre session a expiré. Reconnectez-vous.'});
if(url.pathname==='/api/auth/me')return reply(res,200,{ok:true});
if(url.pathname==='/api/auth/logout'&&req.method==='POST'){const token=/(?:^|;\s*)scola_session=([a-f0-9]{64})/.exec(req.headers.cookie||'')?.[1];if(token)await pool.query('DELETE FROM scola_sessions WHERE token=$1',[hashToken(token)]);res.setHeader('Set-Cookie',cookie('',0));return reply(res,200,{ok:true});}
if(url.pathname!=='/api/school')return reply(res,404,{error:'Page introuvable.'});
if(req.method==='GET'){const results=await Promise.all(['students','payments','reminders','settings'].map(table=>pool.query(`SELECT * FROM scola_${table} WHERE owner=$1${table==='payments'||table==='reminders'?' ORDER BY created DESC':table==='students'?' ORDER BY name':''}`,[owner])));return reply(res,200,{students:results[0].rows,payments:results[1].rows,reminders:results[2].rows,settings:results[3].rows[0]});}
if(req.method!=='POST')return reply(res,405,{error:'Méthode non autorisée.'});const b=await body(req),now=new Date().toISOString(),fail=message=>reply(res,400,{error:message});
if(b.action==='student'){const name=text(b.name),cl=text(b.class_name),parent=text(b.parent),phone=text(b.phone,25),year=text(b.year,20),fee=Number(b.fee);if(!name||!cl||(phone&&!/^\+?[0-9\s-]{8,20}$/.test(phone))||!year||!Number.isSafeInteger(fee)||fee<1||fee>100000000)return fail('Vérifiez les informations de l’élève et les frais.');if(!validSchedule(b.schedule,fee))return fail('Le total des tranches doit correspondre aux frais nets.');await pool.query('INSERT INTO scola_students(id,owner,name,class_name,parent,phone,year,fee,schedule,created) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[randomUUID(),owner,name,cl,parent,phone,year,fee,JSON.stringify(b.schedule),now]);}
else if(b.action==='payment'){const id=text(b.id,50),sid=text(b.student_id,50),amount=Number(b.amount),method=text(b.method),reference=text(b.reference),date=text(b.date);if(!id||!Number.isSafeInteger(amount)||amount<1||!validDate(date)||date>now.slice(0,10)||!['Espèces','Orange Money','Moov Money','Virement','Chèque'].includes(method))return fail('Vérifiez le montant, la date et le moyen de paiement.');if(method!=='Espèces'&&!reference)return fail('La référence de transaction est obligatoire.');const c=await pool.connect();try{await c.query('BEGIN');const s=await c.query('SELECT * FROM scola_students WHERE id=$1 AND owner=$2 FOR UPDATE',[sid,owner]);if(!s.rows.length){await c.query('ROLLBACK');return fail('Élève introuvable.');}const old=await c.query('SELECT id,student_id,amount,method,reference,date FROM scola_payments WHERE id=$1 AND owner=$2',[id,owner]);if(old.rows.length){await c.query('COMMIT');return reply(res,200,{ok:true,id});}const p=await c.query('SELECT COALESCE(SUM(amount),0)::integer AS paid FROM scola_payments WHERE student_id=$1 AND owner=$2 AND cancel_reason IS NULL',[sid,owner]);if(amount>s.rows[0].fee-p.rows[0].paid){await c.query('ROLLBACK');return fail('Le montant dépasse le solde restant.');}await c.query('INSERT INTO scola_payments(id,owner,student_id,amount,method,reference,date,created) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,owner,sid,amount,method,reference,date,now]);await c.query('COMMIT');return reply(res,200,{ok:true,id});}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
else if(b.action==='cancel'){const reason=text(b.reason,300);if(reason.length<5)return fail('Indiquez un motif de 5 caractères minimum.');const result=await pool.query('UPDATE scola_payments SET cancel_reason=$1 WHERE id=$2 AND owner=$3 AND cancel_reason IS NULL',[reason,text(b.id,50),owner]);if(!result.rowCount)return fail('Paiement introuvable ou déjà annulé.');}
else if(b.action==='settings'){if(!text(b.name)||!text(b.year,20))return fail('Indiquez le nom et l’année scolaire.');await pool.query('UPDATE scola_settings SET name=$1,phone=$2,address=$3,year=$4 WHERE owner=$5',[text(b.name),text(b.phone,25),text(b.address,200),text(b.year,20),owner]);}
else if(b.action==='reminder'){const result=await pool.query('INSERT INTO scola_reminders(id,owner,student_id,created) SELECT $1,$2,$3,$4 WHERE EXISTS(SELECT 1 FROM scola_students WHERE id=$3 AND owner=$2)',[randomUUID(),owner,text(b.student_id,50),now]);if(!result.rowCount)return fail('Élève introuvable.');}
else return fail('Action inconnue.');return reply(res,200,{ok:true});}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'");try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/health'){await pool.query('SELECT 1');return reply(res,200,{ok:true});}if(url.pathname.startsWith('/api/'))return await api(req,res,url);if(!['GET','HEAD'].includes(req.method))return reply(res,405,{error:'Méthode non autorisée.'});let path=resolve(staticRoot,'.'+decodeURIComponent(url.pathname));if(!path.startsWith(staticRoot+'/')&&path!==staticRoot)return reply(res,403,{error:'Accès refusé.'});let content;try{content=await readFile(path);}catch{path=resolve(staticRoot,'index.html');content=await readFile(path);}const types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.ico':'image/x-icon'};res.writeHead(200,{'Content-Type':types[extname(path)]||'application/octet-stream','Cache-Control':path.endsWith('.html')?'no-cache':'public,max-age=3600'});res.end(req.method==='HEAD'?undefined:content);}catch(e){console.error('Request failed',e.code||e.name);reply(res,e.status||503,{error:e.status?e.message:'Service temporairement indisponible. Réessayez dans un instant.'});}});
server.listen(Number(process.env.PORT)||3000,'0.0.0.0',()=>console.log('ScolaRecouv ready'));
process.on('SIGTERM',()=>server.close(async()=>{await pool.end();process.exit(0);}));
export {server,pool};
