import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import {audit,insertStudent,studentInput,schoolBackup,validateBackup,snapshot,createMessenger,normalizePhone} from './school-services.mjs';
import pg from 'pg';
import {hashPassword,checkPassword,hashToken,validDate,validSchedule} from './security.mjs';
const production=process.env.NODE_ENV==='production';
if(!process.env.DATABASE_URL){console.error('DATABASE_URL is required. Configure PostgreSQL before starting.');process.exit(1);}
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:10,connectionTimeoutMillis:10000});
await pool.query(await readFile(new URL('./schema.sql',import.meta.url),'utf8'));
const staticRoot=resolve('dist');
const messenger=createMessenger(pool);
async function transaction(fn){const c=await pool.connect();try{await c.query('BEGIN');const result=await fn(c);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
const denied=()=>Object.assign(Error('Cette action est réservée au directeur.'),{status:403});
const attempts=new Map();
const text=(v,max=120)=>typeof v==='string'?v.trim().slice(0,max):'';
const reply=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
function cookie(token,maxAge){return `scola_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${production?'; Secure':''}`;}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>(req.url==='/api/restore'?8000000:1000000))throw Object.assign(Error('Formulaire trop volumineux.'),{status:413});}try{return JSON.parse(raw);}catch{throw Object.assign(Error('Formulaire invalide.'),{status:400});}}
async function user(req){const token=/(?:^|;\s*)scola_session=([a-f0-9]{64})(?:;|$)/.exec(req.headers.cookie||'')?.[1];if(!token)return null;const session=await pool.query('SELECT owner FROM scola_sessions WHERE token=$1 AND expires>now()',[hashToken(token)]);if(!session.rows[0])return null;const account=(await pool.query('SELECT id,login,role,school_owner,display_name,active FROM scola_accounts WHERE id=$1',[session.rows[0].owner])).rows[0];if(!account?.active)return null;return {owner:account.school_owner||account.id,actor:account.id,role:account.role,name:account.display_name||account.login};}
function csrf(req){if(!production&&!req.headers.origin)return true;try{return new URL(req.headers.origin).host===req.headers.host;}catch{return false;}}
async function signIn(res,owner){const token=randomBytes(32).toString('hex');await pool.query('INSERT INTO scola_sessions(token,owner,expires) VALUES($1,$2,now()+interval \'7 days\')',[hashToken(token),owner]);res.setHeader('Set-Cookie',cookie(token,604800));reply(res,200,{ok:true});}
const fallbackHash=await hashPassword(randomBytes(32).toString('hex'));
async function api(req,res,url){if(req.method==='POST'&&!csrf(req))return reply(res,403,{error:'Requête refusée.'});
if(url.pathname==='/api/auth/login'||url.pathname==='/api/auth/register'){if(req.method!=='POST')return reply(res,405,{error:'Méthode non autorisée.'});const b=await body(req),login=text(b.login,60).toLowerCase(),password=typeof b.password==='string'?b.password:'';const ip=(req.headers['x-forwarded-for']||req.socket.remoteAddress||'').toString().split(',').at(-1).trim();const now=Date.now();for(const [k,v]of attempts)if(v.until<now)attempts.delete(k);const keys=['ip:'+ip,'login:'+login];if(keys.some(k=>(attempts.get(k)?.count||0)>=12))return reply(res,429,{error:'Trop de tentatives. Réessayez dans 15 minutes.'});for(const k of keys){const old=attempts.get(k);attempts.set(k,{count:(old?.count||0)+1,until:old?.until||now+900000});}if(attempts.size>10000)attempts.delete(attempts.keys().next().value);
if(!/^[a-z0-9._-]{4,60}$/.test(login)||password.length<1||password.length>128)return reply(res,400,{error:'Vérifiez votre identifiant et votre mot de passe.'});
if(url.pathname.endsWith('register')){const school=text(b.school);if(!school||password.length<10)return reply(res,400,{error:'Indiquez l’école et un mot de passe de 10 caractères minimum.'});const client=await pool.connect();try{await client.query('BEGIN');const id=randomUUID();await client.query('INSERT INTO scola_accounts(id,login,password) VALUES($1,$2,$3)',[id,login,await hashPassword(password)]);await client.query('INSERT INTO scola_settings(owner,name,year) VALUES($1,$2,$3)',[id,school,'2026–2027']);await client.query('COMMIT');return await signIn(res,id);}catch(e){await client.query('ROLLBACK');if(e.code==='23505')return reply(res,409,{error:'Cet identifiant est déjà utilisé. Choisissez-en un autre.'});throw e;}finally{client.release();}}
const r=await pool.query('SELECT id,password,active FROM scola_accounts WHERE login=$1',[login]);const ok=await checkPassword(password,r.rows[0]?.password||fallbackHash);if(!ok||!r.rows[0]?.active)return reply(res,401,{error:'Identifiant ou mot de passe incorrect.'});attempts.delete('login:'+login);return signIn(res,r.rows[0].id);}
const ctx=await user(req);if(!ctx)return reply(res,401,{error:'Votre session a expiré. Reconnectez-vous.'});
const {owner}=ctx;
if(url.pathname==='/api/auth/me')return reply(res,200,{ok:true,role:ctx.role,name:ctx.name});
if(url.pathname==='/api/auth/logout'&&req.method==='POST'){const token=/(?:^|;\s*)scola_session=([a-f0-9]{64})/.exec(req.headers.cookie||'')?.[1];if(token)await pool.query('DELETE FROM scola_sessions WHERE token=$1',[hashToken(token)]);res.setHeader('Set-Cookie',cookie('',0));return reply(res,200,{ok:true});}
if(url.pathname==='/api/backup'&&req.method==='GET'){if(ctx.role!=='director')throw denied();await audit(pool,ctx,'Sauvegarde exportée');return reply(res,200,await schoolBackup(pool,owner));}
if(url.pathname==='/api/snapshot'&&req.method==='GET'){if(ctx.role!=='director')throw denied();const r=await pool.query('SELECT payload FROM scola_snapshots WHERE id=$1 AND owner=$2',[url.searchParams.get('id'),owner]);if(!r.rows.length)return reply(res,404,{error:'Sauvegarde introuvable.'});return reply(res,200,JSON.parse(r.rows[0].payload));}
if(url.pathname==='/api/restore'&&req.method==='POST'){if(ctx.role!=='director')throw denied();const d=validateBackup(await body(req));await transaction(async c=>{await c.query('SELECT owner FROM scola_settings WHERE owner=$1 FOR UPDATE',[owner]);if((await c.query('SELECT id FROM scola_students WHERE owner=$1 LIMIT 1',[owner])).rows.length)throw Object.assign(Error('La restauration nécessite une école vide. Exportez d’abord vos données actuelles ; aucune donnée ne sera écrasée.'),{status:409});const ids=new Map();for(const old of d.students){const id=await insertStudent(c,ctx,studentInput({...old,schedule:JSON.parse(old.schedule)}));ids.set(old.id,id);}let next=Math.max(0,...d.payments.map(p=>p.receipt_number||0))+1;for(const p of d.payments){const number=p.receipt_number||next;next=Math.max(next,number+1);await c.query('INSERT INTO scola_payments(id,owner,student_id,amount,method,reference,date,created,cancel_reason,receipt_number,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[randomUUID(),owner,ids.get(p.student_id),p.amount,p.method,p.reference,p.date,p.created,p.cancel_reason,number,p.created_by||'Import sauvegarde']);}await c.query('UPDATE scola_settings SET name=$1,phone=$2,address=$3,year=$4,next_receipt=$5,reminders_enabled=false,receipts_enabled=false WHERE owner=$6',[d.settings.name,d.settings.phone||'',d.settings.address||'',d.settings.year,next,owner]);for(const r of d.reminders||[])if(ids.has(r.student_id))await c.query('INSERT INTO scola_reminders(id,owner,student_id,created) VALUES($1,$2,$3,$4)',[randomUUID(),owner,ids.get(r.student_id),r.created]);for(const a of d.audit||[])await c.query('INSERT INTO scola_audit(id,owner,actor,event,target,detail,created) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),owner,String(a.actor).slice(0,120),String(a.event).slice(0,120),String(a.target).slice(0,120),String(a.detail).slice(0,500),a.created]);for(const close of d.closings||[])await c.query('INSERT INTO scola_closings(id,owner,day,expected,counted,note,actor,closed,created) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[randomUUID(),owner,close.day,close.expected,close.counted,close.note,close.actor,close.closed,close.created]);await audit(c,ctx,'Sauvegarde restaurée','',d.students.length+' élèves · '+d.payments.length+' paiements');});return reply(res,200,{ok:true});}
if(url.pathname!=='/api/school')return reply(res,404,{error:'Page introuvable.'});
if(req.method==='GET'){if(ctx.role==='director')await snapshot(pool,owner);const results=await Promise.all(['students','payments','reminders','settings'].map(table=>pool.query(`SELECT * FROM scola_${table} WHERE owner=$1${table==='payments'||table==='reminders'?' ORDER BY created DESC':table==='students'?' ORDER BY name':''}`,[owner])));const extra={role:ctx.role,actor:ctx.name,staff:[],audit:[],closings:[],snapshots:[],messages:[],automation:messenger.config()};extra.closings=(await pool.query('SELECT * FROM scola_closings WHERE owner=$1 ORDER BY day DESC LIMIT 30',[owner])).rows;if(ctx.role==='director'){extra.staff=(await pool.query('SELECT id,login,display_name,active FROM scola_accounts WHERE school_owner=$1',[owner])).rows;extra.audit=(await pool.query('SELECT * FROM scola_audit WHERE owner=$1 ORDER BY created DESC LIMIT 100',[owner])).rows;extra.snapshots=(await pool.query('SELECT id,day,created FROM scola_snapshots WHERE owner=$1 ORDER BY day DESC',[owner])).rows;extra.messages=(await pool.query('SELECT id,student_id,kind,status,error,created,updated FROM scola_messages WHERE owner=$1 ORDER BY created DESC LIMIT 100',[owner])).rows;}return reply(res,200,{students:results[0].rows,payments:results[1].rows,reminders:results[2].rows,settings:results[3].rows[0],...extra});}
if(req.method!=='POST')return reply(res,405,{error:'Méthode non autorisée.'});const b=await body(req),now=new Date().toISOString(),fail=message=>reply(res,400,{error:message});
if(['settings','cancel','staff','staff-disable','import','closing','reopen','automation'].includes(b.action)&&ctx.role!=='director')throw denied();
if(b.action==='student'){await transaction(async c=>{await c.query('SELECT owner FROM scola_settings WHERE owner=$1 FOR UPDATE',[owner]);await insertStudent(c,ctx,studentInput(b));});}
else if(b.action==='contact'){const phone=text(b.phone,25),parent=text(b.parent),consent=b.consent===true;if(phone&&!/^\+?[0-9\s-]{8,20}$/.test(phone)||consent&&(!phone||!parent))return fail('Indiquez le parent et son numéro pour les messages.');const r=await pool.query('UPDATE scola_students SET parent=$1,phone=$2,consent=$3,consent_at=$4 WHERE owner=$5 AND id=$6',[parent,phone,consent,consent?now:'',owner,text(b.id,50)]);if(!r.rowCount)return fail('Élève introuvable.');await audit(pool,ctx,'Contact parent modifié',text(b.id,50),consent?'Accord messages renseigné':'Messages désactivés');}
else if(b.action==='import'){if(!Array.isArray(b.students)||!b.students.length||b.students.length>500)return fail('Importez entre 1 et 500 élèves à la fois.');const inputs=b.students.map(studentInput);let added=0,skipped=0;await transaction(async c=>{await c.query('SELECT owner FROM scola_settings WHERE owner=$1 FOR UPDATE',[owner]);const existing=(await c.query('SELECT * FROM scola_students WHERE owner=$1',[owner])).rows;for(const row of inputs){const found=existing.find(s=>s.year===row.year&&(row.external_ref?s.external_ref===row.external_ref:s.name.toLowerCase()===row.name.toLowerCase()&&s.class_name.toLowerCase()===row.class_name.toLowerCase()));if(found){skipped++;continue;}const id=await insertStudent(c,ctx,row);existing.push({...row,id});added++;}await audit(c,ctx,'Liste élèves importée','',added+' ajoutés · '+skipped+' déjà présents');});return reply(res,200,{ok:true,added,skipped});}
else if(b.action==='staff'){const login=text(b.login,60).toLowerCase(),name=text(b.name),password=typeof b.password==='string'?b.password:'';if(!/^[a-z0-9._-]{4,60}$/.test(login)||password.length<10||password.length>128||!name)return fail('Nom, identifiant sans espaces et mot de passe de 10 caractères minimum nécessaires.');try{await transaction(async c=>{const id=randomUUID();await c.query('INSERT INTO scola_accounts(id,login,password,school_owner,role,display_name) VALUES($1,$2,$3,$4,$5,$6)',[id,login,await hashPassword(password),owner,'cashier',name]);await audit(c,ctx,'Accès caissier créé',id,name);});}catch(e){if(e.code==='23505')return fail('Cet identifiant est déjà utilisé.');throw e;}}
else if(b.action==='staff-disable'){await transaction(async c=>{const r=await c.query('UPDATE scola_accounts SET active=false WHERE id=$1 AND school_owner=$2 RETURNING display_name',[text(b.id,50),owner]);if(!r.rows.length)throw Object.assign(Error('Caissier introuvable.'),{status:400});await c.query('DELETE FROM scola_sessions WHERE owner=$1',[text(b.id,50)]);await audit(c,ctx,'Accès caissier désactivé',text(b.id,50),r.rows[0].display_name);});}
else if(b.action==='automation'){if(b.reminders_enabled&&!messenger.config().continuous)return fail('Les rappels programmés nécessitent un hébergement continu.');if((b.reminders_enabled||b.receipts_enabled)&&!messenger.config().ready)return fail('Le service WhatsApp Business n’est pas encore connecté. Aucun message automatique ne sera envoyé.');await pool.query('UPDATE scola_settings SET reminders_enabled=$1,receipts_enabled=$2 WHERE owner=$3',[b.reminders_enabled===true,b.receipts_enabled===true,owner]);await audit(pool,ctx,'Messages automatiques modifiés','',b.reminders_enabled?'Rappels activés':'Rappels désactivés');}
else if(b.action==='closing'){const day=text(b.day),counted=Number(b.counted),note=text(b.note,300);if(!validDate(day)||day>now.slice(0,10)||!Number.isSafeInteger(counted)||counted<0)return fail('Vérifiez la date et le montant compté.');await transaction(async c=>{await c.query('SELECT owner FROM scola_settings WHERE owner=$1 FOR UPDATE',[owner]);const prior=(await c.query('SELECT closed FROM scola_closings WHERE owner=$1 AND day=$2',[owner,day])).rows[0];if(prior?.closed)throw Object.assign(Error('Cette journée est déjà clôturée.'),{status:409});const rows=(await c.query('SELECT amount FROM scola_payments WHERE owner=$1 AND date=$2 AND method=$3 AND cancel_reason IS NULL',[owner,day,'Espèces'])).rows;const expected=rows.reduce((n,p)=>n+p.amount,0);if(expected!==counted&&note.length<5)throw Object.assign(Error('Expliquez l’écart entre le montant attendu et l’argent compté.'),{status:400});await c.query('INSERT INTO scola_closings(id,owner,day,expected,counted,note,actor,created) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(owner,day) DO UPDATE SET expected=EXCLUDED.expected,counted=EXCLUDED.counted,note=EXCLUDED.note,actor=EXCLUDED.actor,closed=true,created=EXCLUDED.created',[randomUUID(),owner,day,expected,counted,note,ctx.name,now]);await audit(c,ctx,'Caisse clôturée',day,'Attendu '+expected+' · Compté '+counted+' · '+note);});}
else if(b.action==='reopen'){if(text(b.note,300).length<5)return fail('Indiquez le motif de réouverture.');await transaction(async c=>{await c.query('SELECT owner FROM scola_settings WHERE owner=$1 FOR UPDATE',[owner]);const r=await c.query('UPDATE scola_closings SET closed=false WHERE owner=$1 AND day=$2 AND closed=true',[owner,text(b.day)]);if(!r.rowCount)throw Object.assign(Error('Journée clôturée introuvable.'),{status:400});await audit(c,ctx,'Caisse rouverte',text(b.day),text(b.note,300));});}
else if(b.action==='payment'){const id=text(b.id,50),sid=text(b.student_id,50),amount=Number(b.amount),method=text(b.method),reference=text(b.reference),date=text(b.date);if(!id||!Number.isSafeInteger(amount)||amount<1||!validDate(date)||date>now.slice(0,10)||!['Espèces','Orange Money','Moov Money','Virement','Chèque'].includes(method))return fail('Vérifiez le montant, la date et le moyen de paiement.');if(method!=='Espèces'&&!reference)return fail('La référence de transaction est obligatoire.');const c=await pool.connect();try{await c.query('BEGIN');const setting=(await c.query('SELECT next_receipt FROM scola_settings WHERE owner=$1 FOR UPDATE',[owner])).rows[0];const s=await c.query('SELECT * FROM scola_students WHERE id=$1 AND owner=$2 FOR UPDATE',[sid,owner]);if(!s.rows.length){await c.query('ROLLBACK');return fail('Élève introuvable.');}const old=await c.query('SELECT * FROM scola_payments WHERE id=$1 AND owner=$2',[id,owner]);if(old.rows.length){const p=old.rows[0];if(p.student_id!==sid||p.amount!==amount||p.method!==method||p.reference!==reference||p.date!==date){await c.query('ROLLBACK');return reply(res,409,{error:'Ce paiement a déjà été enregistré avec d’autres informations. Consultez son reçu.'});}await c.query('COMMIT');return reply(res,200,{ok:true,id,payment:p});}const closed=(await c.query('SELECT closed FROM scola_closings WHERE owner=$1 AND day=$2',[owner,date])).rows[0];if(closed?.closed){await c.query('ROLLBACK');return fail('Cette journée est clôturée. Le directeur doit la rouvrir avant une modification.');}const p=await c.query('SELECT COALESCE(SUM(amount),0)::integer AS paid FROM scola_payments WHERE student_id=$1 AND owner=$2 AND cancel_reason IS NULL',[sid,owner]);if(amount>s.rows[0].fee-p.rows[0].paid){await c.query('ROLLBACK');return fail('Le montant dépasse le solde restant.');}const number=setting.next_receipt;await c.query('UPDATE scola_settings SET next_receipt=next_receipt+1 WHERE owner=$1',[owner]);await c.query('INSERT INTO scola_payments(id,owner,student_id,amount,method,reference,date,created,receipt_number,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,owner,sid,amount,method,reference,date,now,number,ctx.name]);await audit(c,ctx,'Paiement enregistré',id,amount+' FCFA · '+s.rows[0].name+' · SR-'+number);await messenger.queueReceipt(c,owner,sid,id);const payment=(await c.query('SELECT * FROM scola_payments WHERE id=$1 AND owner=$2',[id,owner])).rows[0];await c.query('COMMIT');messenger.dispatch().catch(()=>console.error('Receipt message dispatch failed'));return reply(res,200,{ok:true,id,payment});}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
else if(b.action==='cancel'){const reason=text(b.reason,300);if(reason.length<5)return fail('Indiquez un motif de 5 caractères minimum.');await transaction(async c=>{await c.query('SELECT owner FROM scola_settings WHERE owner=$1 FOR UPDATE',[owner]);const payment=(await c.query('SELECT * FROM scola_payments WHERE id=$1 AND owner=$2 AND cancel_reason IS NULL',[text(b.id,50),owner])).rows[0];if(!payment)throw Object.assign(Error('Paiement introuvable ou déjà annulé.'),{status:400});if((await c.query('SELECT closed FROM scola_closings WHERE owner=$1 AND day=$2',[owner,payment.date])).rows[0]?.closed)throw Object.assign(Error('Rouvrez la journée de caisse avant d’annuler ce paiement.'),{status:409});await c.query('UPDATE scola_payments SET cancel_reason=$1 WHERE id=$2 AND owner=$3',[reason,payment.id,owner]);await audit(c,ctx,'Paiement annulé',payment.id,reason);});}
else if(b.action==='settings'){if(!text(b.name)||!text(b.year,20))return fail('Indiquez le nom et l’année scolaire.');await pool.query('UPDATE scola_settings SET name=$1,phone=$2,address=$3,year=$4 WHERE owner=$5',[text(b.name),text(b.phone,25),text(b.address,200),text(b.year,20),owner]);await audit(pool,ctx,'École modifiée');}
else if(b.action==='reminder'){const result=await pool.query('INSERT INTO scola_reminders(id,owner,student_id,created) SELECT $1,$2,$3,$4 WHERE EXISTS(SELECT 1 FROM scola_students WHERE id=$3 AND owner=$2)',[randomUUID(),owner,text(b.student_id,50),now]);if(!result.rowCount)return fail('Élève introuvable.');}
else return fail('Action inconnue.');return reply(res,200,{ok:true});}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'");try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/health'){await pool.query('SELECT 1');return reply(res,200,{ok:true});}if(url.pathname==='/api/automation/run'){const key=process.env.AUTOMATION_SECRET||'',given=String(req.headers['x-automation-key']||'');if(req.method!=='POST'||key.length<32||Buffer.byteLength(key)!==Buffer.byteLength(given)||!timingSafeEqual(Buffer.from(key),Buffer.from(given)))return reply(res,403,{error:'Accès refusé.'});await messenger.run();return reply(res,200,{ok:true});}if(url.pathname.startsWith('/api/'))return await api(req,res,url);if(!['GET','HEAD'].includes(req.method))return reply(res,405,{error:'Méthode non autorisée.'});let path=resolve(staticRoot,'.'+decodeURIComponent(url.pathname));if(!path.startsWith(staticRoot+'/')&&path!==staticRoot)return reply(res,403,{error:'Accès refusé.'});let content;try{content=await readFile(path);}catch{path=resolve(staticRoot,'index.html');content=await readFile(path);}const types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.ico':'image/x-icon','.webmanifest':'application/manifest+json'};res.writeHead(200,{'Content-Type':types[extname(path)]||'application/octet-stream','Cache-Control':path.endsWith('.html')||path.endsWith('/sw.js')?'no-cache':'public,max-age=3600'});res.end(req.method==='HEAD'?undefined:content);}catch(e){console.error('Request failed',e.code||e.name);reply(res,e.status||503,{error:e.status?e.message:'Service temporairement indisponible. Réessayez dans un instant.'});}});
let timer;if(process.env.SCHOOL_AUTOMATION_ENABLED==='true'){timer=setInterval(()=>messenger.run().catch(()=>console.error('Scheduled school task failed')),60000);timer.unref();}
server.listen(Number(process.env.PORT)||3000,'0.0.0.0',()=>console.log('ScolaRecouv ready'));
process.on('SIGTERM',()=>{if(timer)clearInterval(timer);server.close(async()=>{await pool.end();process.exit(0);});});
export {server,pool};
