import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newDb} from 'pg-mem';
import pg from 'pg';
const db=newDb();pg.Pool=db.adapters.createPg().Pool;
process.env.DATABASE_URL='postgresql://test';process.env.PORT='3097';process.env.NODE_ENV='development';
const {server,pool}=await import('../server.mjs');
async function call(path,body,cookie){const r=await fetch('http://127.0.0.1:3097'+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
test('Independent account, tuition payments, receipt data, cancellation and school isolation',async()=>{try{
assert.equal((await call('/api/school')).status,401);
const account=await call('/api/auth/register',{login:'test-school',password:'SchoolPass123!',school:'École Test'});assert.equal(account.status,200,JSON.stringify(account.body));assert.ok(account.cookie);const cookie=account.cookie;
assert.equal((await call('/api/auth/login',{login:'test-school',password:'bad'})).status,401);
assert.equal((await call('/api/auth/login',{login:'test-school',password:'SchoolPass123!'})).status,200);
assert.equal((await call('/api/school',{action:'student',name:'Test Élève',class_name:'CP1',parent:'Test Parent',phone:'70123456',year:'2026–2027',fee:90000,schedule:[{date:'2026-10-05',amount:30000},{date:'2027-01-05',amount:60000}]},cookie)).status,200);
let d=(await call('/api/school',null,cookie)).body;const sid=d.students[0].id;assert.equal(d.settings.name,'École Test');
const payment={action:'payment',id:'payment-1',student_id:sid,amount:30000,method:'Espèces',reference:'',date:'2026-10-05'};
assert.equal((await call('/api/school',payment,cookie)).status,200);
assert.equal((await call('/api/school',payment,cookie)).status,200);
assert.equal((await call('/api/school',{...payment,id:'overpayment',amount:70000},cookie)).status,400);
d=(await call('/api/school',null,cookie)).body;assert.equal(d.payments.length,1);assert.equal(d.payments[0].amount,30000);
const other=await call('/api/auth/register',{login:'other-school',password:'SchoolPass123!',school:'Autre école'});assert.equal(other.status,200);
assert.equal((await call('/api/school',null,other.cookie)).body.students.length,0);
assert.equal((await call('/api/school',{...payment,id:'foreign'},other.cookie)).status,400);
assert.equal((await call('/api/school',{action:'cancel',id:'payment-1',reason:'Erreur de caisse'},cookie)).status,200);
assert.equal((await call('/api/school',{...payment,id:'payment-2',amount:90000},cookie)).status,200);
const simple={action:'student',name:'Simple Élève',class_name:'CP2',parent:'',phone:'',year:'2026–2027',fee:80000,schedule:[{date:'2027-06-30',amount:80000}]};
assert.equal((await call('/api/school',simple,cookie)).status,200);
const simpleStudent=(await call('/api/school',null,cookie)).body.students.find(s=>s.name==='Simple Élève');assert.equal(simpleStudent.phone,'');assert.equal(simpleStudent.parent,'');
assert.equal((await call('/api/school',{...payment,id:'simple-payment',student_id:simpleStudent.id,amount:10000},cookie)).status,200);
assert.equal((await call('/api/school',{...simple,name:'Invalid Phone',phone:'abc'},cookie)).status,400);

assert.equal((await call('/api/school',{action:'staff',login:'test-cashier',name:'Aminata Caisse',password:'CashierPass123!'},cookie)).status,200);
const cashier=await call('/api/auth/login',{login:'test-cashier',password:'CashierPass123!'});assert.equal(cashier.status,200);
assert.equal((await call('/api/auth/me',null,cashier.cookie)).body.role,'cashier');
const cashierData=(await call('/api/school',null,cashier.cookie)).body;assert.equal(cashierData.students.length,2);assert.equal(cashierData.staff.length,0);assert.equal(cashierData.audit.length,0);
for(const action of ['settings','cancel','staff','import','closing','automation'])assert.equal((await call('/api/school',{action},cashier.cookie)).status,403,action);
assert.equal((await call('/api/backup',null,cashier.cookie)).status,403);
const cashPayment={...payment,id:'cashier-pay',student_id:simpleStudent.id,amount:20000};
const cp=await call('/api/school',cashPayment,cashier.cookie);assert.equal(cp.status,200);assert.equal(cp.body.payment.created_by,'Aminata Caisse');assert.ok(cp.body.payment.receipt_number);
assert.equal((await call('/api/school',{...cashPayment,amount:25000},cashier.cookie)).status,409);
assert.equal((await call('/api/school',{action:'closing',day:'2026-10-05',counted:120000,note:''},cookie)).status,200);
assert.equal((await call('/api/school',{...payment,id:'after-close',student_id:simpleStudent.id,amount:1000},cashier.cookie)).status,400);
assert.equal((await call('/api/school',{action:'cancel',id:'cashier-pay',reason:'Erreur de saisie'},cookie)).status,409);
assert.equal((await call('/api/school',{action:'reopen',day:'2026-10-05',note:'Correction du paiement'},cookie)).status,200);
assert.equal((await call('/api/school',{action:'cancel',id:'cashier-pay',reason:'Erreur de saisie'},cookie)).status,200);
const imported={name:'Import Élève',class_name:'CM2',parent:'Parent Import',phone:'70111222',year:'2026–2027',fee:60000,schedule:[{date:'2027-06-30',amount:60000}]};
const imp=await call('/api/school',{action:'import',students:[imported,imported]},cookie);assert.equal(imp.status,200);assert.equal(imp.body.added,1);assert.equal(imp.body.skipped,1);
const repeated=await call('/api/school',{action:'import',students:[imported]},cookie);assert.equal(repeated.body.added,0);assert.equal(repeated.body.skipped,1);
assert.equal((await call('/api/school',{action:'automation',receipts_enabled:true},cookie)).status,400);
const backup=await call('/api/backup',null,cookie);assert.equal(backup.status,200);assert.equal(backup.body.data.students.length,3);assert.equal(backup.body.format,'scolarecouv');assert.ok(!JSON.stringify(backup.body).includes('SchoolPass123'));assert.ok(!backup.body.data.accounts);
assert.equal((await call('/api/restore',backup.body,cookie)).status,409);
const emptySchool=await call('/api/auth/register',{login:'restore-school',password:'SchoolPass123!',school:'École vide'});assert.equal(emptySchool.status,200);
const corrupted=structuredClone(backup.body);corrupted.data.students[0].fee=1;assert.equal((await call('/api/restore',corrupted,emptySchool.cookie)).status,400);
const restored=await call('/api/restore',backup.body,emptySchool.cookie);assert.equal(restored.status,200,JSON.stringify(restored.body));const restoredData=(await call('/api/school',null,emptySchool.cookie)).body;assert.equal(restoredData.students.length,3);assert.equal(restoredData.payments.length,4);assert.equal(restoredData.settings.receipts_enabled,false);assert.equal(restoredData.settings.name,'École Test');
const directorData=(await call('/api/school',null,cookie)).body;assert.ok(directorData.audit.some(a=>a.event==='Paiement annulé'));assert.ok(directorData.snapshots.length);
const staffId=directorData.staff[0].id;assert.equal((await call('/api/school',{action:'staff-disable',id:staffId},cookie)).status,200);assert.equal((await call('/api/auth/me',null,cashier.cookie)).status,401);
assert.equal((await call('/api/automation/run',{},cookie)).status,403);
assert.equal((await call('/api/auth/logout',{},cookie)).status,200);
assert.equal((await call('/api/school',null,cookie)).status,401);
}finally{await new Promise(resolve=>server.close(resolve));await pool.end();}});
