import {useEffect,useState} from 'react';
import Director,{type DirectorData} from './Director';
import {request} from './network';
import {GraduationCap,Home,Users,Wallet,MessageCircle,Settings,Plus,Search,Download,Printer,X,ChevronRight,ArrowLeft,CheckCircle2,MoreHorizontal} from 'lucide-react';
type Student={id:string;name:string;class_name:string;parent:string;phone:string;year:string;fee:number;schedule:string;consent?:boolean;external_ref?:string};
type Payment={id:string;student_id:string;amount:number;method:string;reference:string;date:string;created:string;cancel_reason:string|null;receipt_number?:number;created_by?:string};
type Data=DirectorData & {students:Student[];payments:Payment[];reminders:{student_id:string;created:string}[];settings:{name:string;phone:string;address:string;year:string}};
const money=(n:number)=>new Intl.NumberFormat('fr-FR').format(n)+' FCFA';
const searchText=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase().trim();
const today=()=>new Date().toISOString().slice(0,10);
const displayDate=(d:string)=>new Date(d.slice(0,10)+'T12:00:00').toLocaleDateString('fr-FR');
const empty:Data={students:[],payments:[],reminders:[],settings:{name:'Mon école',phone:'',address:'',year:'2026–2027'}};
const nav=[{key:'dashboard',label:'Accueil',icon:Home},{key:'students',label:'Élèves',icon:Users},{key:'reminders',label:'Impayés',icon:Wallet},{key:'more',label:'Plus',icon:MoreHorizontal}];
export default function School({onLogout}:{onLogout:()=>Promise<void>}){
const [data,setData]=useState<Data>(empty),[view,setView]=useState('dashboard'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[payQuery,setPayQuery]=useState(''),[modal,setModal]=useState(''),[selected,setSelected]=useState(''),[receipt,setReceipt]=useState<Payment|null>(null),[paymentId,setPaymentId]=useState(''),[year,setYear]=useState(''),[method,setMethod]=useState('Espèces'),[split,setSplit]=useState(false),[remindStudent,setRemindStudent]=useState<Student|null>(null),[message,setMessage]=useState('');
async function load(){setLoading(true);try{const r=await request('/api/school');const d=await r.json();if(r.status===401){window.location.reload();return;}if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{load();},[]);
const currentYear=year||data.settings.year;
const isDirector=data.role!=='cashier';
const directorViews=['daily','team','import','messages','backup','audit','families'];
const students=data.students.filter(s=>s.year===currentYear);
const classes=[...new Set(students.map(s=>s.class_name))].sort();
const years=[...new Set([data.settings.year,...data.students.map(s=>s.year)])];
const deadline=()=>{const last=currentYear.match(/\d{4}/g)?.at(-1);return last?last+'-06-30':today();};
function paid(s:Student){return data.payments.filter(p=>p.student_id===s.id&&!p.cancel_reason).reduce((a,p)=>a+p.amount,0);}
function balance(s:Student){return Math.max(0,s.fee-paid(s));}
function due(s:Student){return Math.max(0,JSON.parse(s.schedule).filter((e:{date:string;amount:number})=>e.date<=today()).reduce((a:number,e:{amount:number})=>a+e.amount,0)-paid(s));}
const remaining=students.filter(s=>balance(s)>0),collected=students.reduce((a,s)=>a+paid(s),0),rest=students.reduce((a,s)=>a+balance(s),0);
const filtered=(view==='reminders'?remaining:students).filter(s=>searchText(s.name+' '+s.class_name+' '+s.parent+' '+s.phone+' '+(s.external_ref||'')).includes(searchText(query)));
const payMatches=remaining.filter(s=>searchText(s.name+' '+s.class_name+' '+s.parent+' '+s.phone+' '+(s.external_ref||'')).includes(searchText(payQuery)));
const homeMatches=students.filter(s=>searchText(s.name+' '+s.class_name+' '+s.parent+' '+s.phone+' '+(s.external_ref||'')).includes(searchText(query)));
const receivedToday=data.payments.filter(p=>p.date===today()&&!p.cancel_reason).reduce((n,p)=>n+p.amount,0);
const payments=data.payments.filter(p=>students.some(s=>s.id===p.student_id));
const currentStudent=data.students.find(s=>s.id===selected);
async function save(body:Record<string,unknown>){setBusy(true);setError('');try{const r=await request('/api/school',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);await load();return d;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
function go(key:string){setView(key);setQuery('');setError('');setNotice('');}
function addStudent(){setSplit(false);setError('');setModal('student');}
function openPay(sid=''){setSelected(sid);setPayQuery('');setMethod('Espèces');setPaymentId(crypto.randomUUID());setError('');setModal('payment');}
function close(){setModal('');setError('');}
function exportCsv(){const rows=[['Élève','Classe','Parent','Téléphone','Année','Scolarité','Payé','Reste à payer'],...students.map(s=>[s.name,s.class_name,s.parent,s.phone,s.year,s.fee,paid(s),balance(s)])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@\-]/,"'$&").replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='scolarite-'+currentYear+'.csv';a.click();URL.revokeObjectURL(url);}
function prepare(s:Student){setRemindStudent(s);const amount=due(s)||balance(s);setMessage(`Bonjour${s.parent?' '+s.parent:''}, le reste à payer pour la scolarité de ${s.name} (${s.class_name}) est de ${money(balance(s))}.${due(s)?' Dont '+money(amount)+' arrivé à échéance.':''} Merci de contacter ${data.settings.name} pour le prochain versement. Si vous avez déjà payé, merci de nous communiquer la référence du paiement.`);setModal('reminder');}
const receiptStudent=receipt?data.students.find(s=>s.id===receipt.student_id):null;
return <div className="app simple-app"><aside className="sidebar"><div className="brand"><span className="brand-icon"><GraduationCap size={25}/></span><div>Scola<span>Recouv</span></div></div><div className="school-name">{data.settings.name}</div><nav>{nav.map(n=><button key={n.key} className={'nav '+(view===n.key||n.key==='more'&&['settings','payments',...directorViews].includes(view)?'active':'')} onClick={()=>go(n.key)}><n.icon size={22}/><span>{n.label}</span></button>)}</nav><button className="logout" onClick={onLogout}>Se déconnecter</button></aside><div className="workspace"><header><div className="mobile-brand"><GraduationCap/> ScolaRecouv</div><span className="simple-school">{data.settings.name}<small className="actor-note">{data.actor} · {isDirector?'Directeur':'Caissier'}</small></span></header><main>
{error&&!modal&&<div className="error" role="alert">{error}<button aria-label="Fermer" onClick={()=>setError('')}><X size={16}/></button></div>}
{notice&&<div className="notice" role="status"><CheckCircle2 size={18}/>{notice}<button aria-label="Fermer" onClick={()=>setNotice('')}><X size={16}/></button></div>}
<div className="page-heading"><div><h1>{view==='dashboard'?'Bonjour 👋':view==='students'?'Mes élèves':view==='reminders'?'Qui doit encore payer ?':view==='payments'?'Les paiements reçus':view==='settings'?'Mon école':view==='daily'?'Ma journée':view==='team'?'Mon équipe':view==='import'?'Importer mes élèves':view==='messages'?'Messages automatiques':view==='backup'?'Mes sauvegardes':view==='audit'?'Historique':view==='families'?'Les familles':'Autres actions'}</h1>{view==='dashboard'&&<p>Votre école, en quelques gestes.</p>}</div>{view==='students'&&<button className="primary" disabled={loading} onClick={addStudent}><Plus size={18}/> Ajouter un élève</button>}</div>
{loading?<div className="empty">Ouverture de votre école…</div>:<>
{view==='dashboard'&&<><label className="search simple-search home-search"><Search size={20}/><input aria-label="Rechercher un élève à l’accueil" placeholder="Nom de l’élève ou téléphone du parent…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-btn" aria-label="Effacer la recherche" onClick={()=>setQuery('')}><X size={18}/></button>}</label>{query.trim()?<section className="lookup-list" aria-label="Résultats de la recherche">{homeMatches.slice(0,6).map(s=><div className="lookup-row" key={s.id}><button className="lookup-name" onClick={()=>{setSelected(s.id);setModal('detail');}}><b>{s.name}</b><small>{s.class_name} · {balance(s)?'Reste '+money(balance(s)):'Tout payé'}</small></button>{balance(s)>0&&<button className="primary" onClick={()=>openPay(s.id)}>Encaisser</button>}</div>)}{!homeMatches.length&&<p>Aucun élève trouvé. Essayez son nom ou le téléphone du parent.</p>}{homeMatches.length>6&&<p>Précisez le nom pour afficher les autres élèves.</p>}</section>:<><div className="quick-actions everyday-actions"><button className="main-action" onClick={()=>openPay()}><span className="quick-icon"><Wallet size={26}/></span><b>Encaisser</b><small>Enregistrer un versement</small><ChevronRight className="quick-arrow"/></button><button onClick={addStudent}><span className="quick-icon"><Plus size={26}/></span><b>Ajouter un élève</b><small>Trois informations suffisent</small><ChevronRight className="quick-arrow"/></button></div>{!students.length?<div className="start-guide"><span className="step-circle">1</span><div><b>Ajoutez votre premier élève.</b><p>Le reste à payer se calculera tout seul.</p></div></div>:<div className="home-summary"><div><span>Reçu aujourd’hui</span><strong>{money(receivedToday)}</strong>{isDirector&&<button className="text-btn" onClick={()=>go('daily')}>Voir ma journée <ChevronRight size={16}/></button>}</div><button onClick={()=>go('reminders')}><span>Reste à recevoir</span><strong>{money(rest)}</strong><small>{remaining.length} élèves · Voir les impayés <ChevronRight size={16}/></small></button></div>}<button className="home-list-link text-btn" onClick={()=>go('students')}>Mes élèves ({students.length}) <ChevronRight size={18}/></button></>}</>}
{(view==='students'||view==='reminders')&&<><label className="search simple-search"><Search size={20}/><input aria-label="Rechercher un élève" placeholder="Nom, classe ou téléphone du parent…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{view==='reminders'&&<p className="plain-help">Voici les élèves dont la scolarité n’est pas entièrement payée.</p>}<div className="student-cards">{filtered.map(s=><article className="student-card" key={s.id}><div className="student-card-top"><button className="student-link" onClick={()=>{setSelected(s.id);setModal('detail');}}>{s.name}<small>{s.class_name}</small></button><span className={'badge '+(balance(s)===0?'green':'blue')}>{balance(s)===0?'Tout payé':'Reste '+money(balance(s))}</span></div><p>Payé : {money(paid(s))} sur {money(s.fee)}</p><div className="actions">{balance(s)>0&&<button className="primary" onClick={()=>openPay(s.id)}>Encaisser</button>}{view==='reminders'&&s.phone&&<button className="secondary" onClick={()=>prepare(s)}><MessageCircle size={16}/> Rappeler au parent</button>}<button className="text-btn" onClick={()=>{setSelected(s.id);setModal('detail');}}>Voir le dossier <ChevronRight size={16}/></button></div></article>)}</div>{!filtered.length&&<div className="empty"><Users size={32}/><h3>{query?'Aucun élève trouvé.':view==='reminders'?'Aucun reste à payer.':'Votre liste est vide.'}</h3><p>{query?'Essayez un autre nom.':view==='reminders'?'Tous les élèves de cette année ont réglé leur scolarité.':'Ajoutez votre premier élève pour commencer.'}</p>{!query&&view==='students'&&<button className="primary" onClick={addStudent}>Ajouter un élève</button>}</div>}</>}
{view==='more'&&<section className="panel simple-menu"><p>Les outils utiles, quand vous en avez besoin.</p>{isDirector&&<button onClick={()=>go('daily')}><Wallet/><span>Ma journée<small>Recettes et clôture de caisse</small></span><ChevronRight/></button>}<button onClick={()=>go('payments')}><Printer/><span>Retrouver un reçu</span><ChevronRight/></button>{isDirector&&<button onClick={()=>go('families')}><Users/><span>Les familles<small>Les enfants d’un même parent</small></span><ChevronRight/></button>}<details className="management-menu"><summary>{isDirector?'Gérer mon école':'Listes et année scolaire'}</summary>{isDirector&&<><button onClick={()=>go('team')}><Users/><span>Mon équipe</span><ChevronRight/></button><button onClick={()=>go('import')}><Plus/><span>Importer des élèves</span><ChevronRight/></button><button onClick={()=>go('messages')}><MessageCircle/><span>Messages automatiques</span><ChevronRight/></button><button onClick={()=>go('backup')}><Download/><span>Sauvegarder ou restaurer</span><ChevronRight/></button><button onClick={()=>go('audit')}><CheckCircle2/><span>Historique des opérations</span><ChevronRight/></button><button onClick={()=>go('settings')}><Settings/><span>Informations de l’école</span><ChevronRight/></button></>}<button onClick={exportCsv}><Download/><span>Télécharger la liste Excel</span><ChevronRight/></button><label>Année scolaire<select value={currentYear} onChange={e=>setYear(e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></label></details><button onClick={onLogout}><ArrowLeft/><span>Se déconnecter</span></button></section>}
{view==='payments'&&<><button className="text-btn back-link" onClick={()=>go('more')}><ArrowLeft size={17}/> Retour</button>{payments.map(p=><article className="student-card" key={p.id}><div className="student-card-top"><b>{data.students.find(s=>s.id===p.student_id)?.name}</b><b>{money(p.amount)}</b></div><p>{displayDate(p.date)} · {p.method}{p.cancel_reason?' · Annulé':''}<small className="actor-note">{p.created_by||'Ancien paiement'} · {p.receipt_number?'SR-'+String(p.receipt_number).padStart(6,'0'):''}</small></p><div className="actions"><button className="primary" onClick={()=>{setReceipt(p);setModal('receipt');}}><Printer size={17}/> Voir le reçu</button>{isDirector&&!p.cancel_reason&&<button className="text-btn" onClick={()=>{setReceipt(p);setModal('cancel');}}>Annuler ce paiement</button>}</div>{p.cancel_reason&&<p>Motif : {p.cancel_reason}</p>}</article>)}{!payments.length&&<div className="empty"><h3>Aucun paiement pour le moment.</h3><button className="primary" onClick={()=>openPay()}>Encaisser</button></div>}</>}
{isDirector&&view==='settings'&&<section className="panel settings-panel"><button className="text-btn back-link" onClick={()=>go('more')}><ArrowLeft size={17}/> Retour</button><form onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(await save({action:'settings',...f})){setYear('');setNotice('Les informations de votre école sont enregistrées.');go('dashboard');setNotice('Les informations de votre école sont enregistrées.');}}}><label>Nom de l’école<input name="name" required defaultValue={data.settings.name}/></label><label>Année scolaire<input name="year" required defaultValue={data.settings.year}/></label><details className="optional-fields"><summary>Téléphone et adresse · facultatif</summary><label>Téléphone<input name="phone" defaultValue={data.settings.phone}/></label><label>Adresse<input name="address" defaultValue={data.settings.address}/></label></details><button className="primary full" disabled={busy}>Enregistrer</button></form></section>}
</>}
{isDirector&&directorViews.includes(view)&&<Director key={view} data={data} year={currentYear} view={view} go={go} save={save} refresh={load} openPay={openPay}/>}
</main></div>
{modal&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label={modal==='student'?'Ajouter un élève':modal==='payment'?'Encaisser':'Dossier et reçu'} className={'modal '+(modal==='receipt'?'receipt-modal':'')}><button className="close icon-btn" aria-label="Fermer" disabled={busy} onClick={close}><X/></button>{error&&<div className="error" role="alert">{error}</div>}
{modal==='student'&&<><h2>Ajouter un élève</h2><p>Remplissez ces trois informations.</p><form onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const fee=Number(f.fee);const schedule=split?[1,2,3].map(i=>({amount:Number(f['a'+i]),date:f['d'+i]})).filter(s=>s.amount>0):[{amount:fee,date:f.deadline||deadline()}];if(await save({action:'student',...f,fee,parent:f.parent||'',phone:f.phone||'',consent:f.consent==='on',year:currentYear,schedule})){close();setView('students');setNotice(String(f.name)+' a été ajouté. Vous pouvez enregistrer son premier paiement.');}}}><label>Nom de l’élève<input name="name" required autoFocus placeholder="Ex. Aïcha Ouédraogo"/></label><label>Classe<input name="class_name" required placeholder="Ex. CP1" list="class-list"/><datalist id="class-list">{classes.map(c=><option key={c}>{c}</option>)}</datalist></label><label>Scolarité pour l’année (FCFA)<input type="number" inputMode="numeric" name="fee" min="1" max="100000000" step="1" required placeholder="Ex. 90 000"/></label><details className="optional-fields"><summary>Parent et dates de paiement · facultatif</summary><label>Nom du parent<input name="parent" placeholder="À compléter si vous le souhaitez"/></label><label>Téléphone du parent<input name="phone" type="tel" placeholder="Ex. +226 70 00 00 00"/></label><label className="checkbox"><input name="consent" type="checkbox"/> Le parent a accepté de recevoir ses reçus et rappels de scolarité sur WhatsApp.</label><p className="form-hint">Les paiements partiels sont toujours possibles, même sans définir de tranches.</p><label className="checkbox"><input type="checkbox" checked={split} onChange={e=>setSplit(e.target.checked)}/> Définir des paiements par tranches</label>{split?<><p className="form-hint">Le total des tranches doit égaler la scolarité.</p>{[1,2,3].map(i=><div className="form-grid" key={i}><label>Tranche {i} (FCFA)<input name={'a'+i} type="number" inputMode="numeric" min="0" step="1" defaultValue={0} required/></label><label>Date limite<input name={'d'+i} type="date" defaultValue={i===1?today():''}/></label></div>)}</>:<label>Date limite de la scolarité<input name="deadline" type="date" defaultValue={deadline()}/><small>Par défaut : fin de l’année scolaire.</small></label>}</details><button className="primary full" disabled={busy}>{busy?'Enregistrement…':'Ajouter cet élève'}</button></form></>}
{modal==='payment'&&<><h2>Encaisser</h2>{!remaining.length?<><p>{students.length?'Tous les élèves ont réglé leur scolarité.':'Ajoutez d’abord un élève pour enregistrer son paiement.'}</p><button className="primary full" onClick={students.length?close:addStudent}>{students.length?'Fermer':'Ajouter un élève'}</button></>:<form onSubmit={async e=>{e.preventDefault();if(!selected)return;const f=Object.fromEntries(new FormData(e.currentTarget));const payment:Payment={id:paymentId,student_id:selected,amount:Number(f.amount),method,reference:String(f.reference||''),date:String(f.date||today()),created:new Date().toISOString(),cancel_reason:null};const result=await save({action:'payment',...payment});if(result){setReceipt(result.payment||payment);setModal('receipt');setNotice('Paiement enregistré. Le reste à payer est mis à jour.');}}}>{currentStudent?<><div className="payment-student"><b>{currentStudent.name}</b><small>{currentStudent.class_name}</small><button type="button" className="text-btn" onClick={()=>setSelected('')}>Changer d’élève</button></div><div className="balance">Reste à payer <b>{money(balance(currentStudent))}</b></div></>:<div className="payment-picker"><p>Quel élève règle sa scolarité ?</p><label className="search simple-search"><Search size={20}/><input autoFocus aria-label="Chercher l’élève qui paie" placeholder="Son nom ou le téléphone du parent…" value={payQuery} onChange={e=>setPayQuery(e.target.value)}/></label><div className="lookup-list">{payMatches.slice(0,6).map(s=><button type="button" className="picker-row" key={s.id} onClick={()=>setSelected(s.id)}><span><b>{s.name}</b><small>{s.class_name} · Reste {money(balance(s))}</small></span><ChevronRight size={20}/></button>)}{!payMatches.length&&<p>Aucun élève trouvé parmi les scolarités restant à payer.</p>}{payMatches.length>6&&<p>Tapez un nom pour retrouver l’élève.</p>}</div></div>}{currentStudent&&<><label>Montant reçu (FCFA)<input autoFocus name="amount" type="number" inputMode="numeric" min="1" step="1" required max={currentStudent?balance(currentStudent):undefined} placeholder="Ex. 10 000"/></label><label>Comment avez-vous reçu l’argent ?<select value={method} onChange={e=>setMethod(e.target.value)}>{['Espèces','Orange Money','Moov Money','Virement','Chèque'].map(m=><option key={m}>{m}</option>)}</select></label>{method!=='Espèces'&&<label>Référence de la transaction<input name="reference" required placeholder="Le numéro indiqué sur le paiement"/></label>}<details className="optional-fields"><summary>Modifier la date · facultatif</summary><label>Date du paiement<input name="date" type="date" required max={today()} defaultValue={today()}/></label></details><p className="plain-help">Enregistrez uniquement l’argent que vous avez reçu et vérifié.</p><button className="primary full" disabled={busy||!selected}>{busy?'Enregistrement…':'Enregistrer le versement'}</button></>}</form>}</>}
{modal==='detail'&&currentStudent&&<><h2>{currentStudent.name}</h2><p>{currentStudent.class_name} · {currentStudent.year}</p><div className="balance">Scolarité <b>{money(currentStudent.fee)}</b></div><div className="balance">Déjà payé <b>{money(paid(currentStudent))}</b></div><div className="balance">Reste à payer <b>{money(balance(currentStudent))}</b></div>{balance(currentStudent)>0&&<button className="primary full" onClick={()=>openPay(currentStudent.id)}>Encaisser</button>}<h3>Ses paiements</h3>{data.payments.filter(p=>p.student_id===currentStudent.id).map(p=><div className="balance" key={p.id}><span>{displayDate(p.date)}{p.cancel_reason?' · Annulé':''}</span><button className="text-btn" onClick={()=>{setReceipt(p);setModal('receipt');}}>{money(p.amount)} · Reçu</button></div>)}{!data.payments.some(p=>p.student_id===currentStudent.id)&&<p>Aucun paiement enregistré.</p>}<details className="optional-fields"><summary>Parent et échéances</summary><form key={currentStudent.id+currentStudent.phone+String(currentStudent.consent)} onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(await save({action:'contact',id:currentStudent.id,parent:f.parent,phone:f.phone,consent:f.consent==='on'}))setNotice('Le contact du parent est enregistré.');}}><label>Nom du parent<input name="parent" defaultValue={currentStudent.parent}/></label><label>Téléphone<input name="phone" type="tel" defaultValue={currentStudent.phone}/></label><label className="checkbox"><input type="checkbox" name="consent" defaultChecked={currentStudent.consent}/> Le parent a accepté les reçus et rappels WhatsApp.</label><button className="secondary full" disabled={busy}>Enregistrer le contact</button></form>{JSON.parse(currentStudent.schedule).map((e:{date:string;amount:number},i:number)=><div className="balance" key={i}><span>{displayDate(e.date)}</span><b>{money(e.amount)}</b></div>)}{currentStudent.phone&&balance(currentStudent)>0&&<button className="secondary full" onClick={()=>prepare(currentStudent)}>Rappeler au parent</button>}<h3>Rappels notés comme envoyés</h3>{data.reminders.filter(r=>r.student_id===currentStudent.id).map((r,i)=><p key={i}>{displayDate(r.created)}</p>)}</details><button className="secondary full" onClick={close}>Fermer le dossier</button></>}
{modal==='reminder'&&remindStudent&&<><h2>Rappeler au parent</h2><p>Pour {remindStudent.name}</p><label>Votre message<textarea rows={6} value={message} onChange={e=>setMessage(e.target.value)}/></label><a className="primary full" href={'https://wa.me/'+((remindStudent.phone.replace(/\D/g,'').length===8?'226':'')+remindStudent.phone.replace(/\D/g,''))+'?text='+encodeURIComponent(message)} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Ouvrir WhatsApp</a><p className="plain-help">Envoyez le message dans WhatsApp, puis revenez ici.</p><button className="secondary full" disabled={busy} onClick={async()=>{if(await save({action:'reminder',student_id:remindStudent.id})){close();setNotice('Rappel noté comme envoyé.');}}}>J’ai envoyé le rappel</button></>}
{modal==='cancel'&&receipt&&<><h2>Annuler ce paiement ?</h2><p>{money(receipt.amount)} · {data.students.find(s=>s.id===receipt.student_id)?.name}</p><p>Le paiement restera dans l’historique. Son montant sera remis dans le reste à payer.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await save({action:'cancel',id:receipt.id,reason:f.get('reason')})){close();setNotice('Paiement annulé. Le reste à payer est mis à jour.');}}}><label>Pourquoi l’annuler ?<textarea name="reason" required minLength={5} rows={3}/></label><button className="primary full" disabled={busy}>Confirmer l’annulation</button><button className="secondary full" type="button" onClick={close}>Garder ce paiement</button></form></>}
{modal==='receipt'&&receipt&&receiptStudent&&<><div className="receipt-success"><CheckCircle2 size={28}/><b>{receipt.cancel_reason?'Paiement annulé':'Paiement enregistré'}</b></div><div className="payment-confirmation"><h2>{receiptStudent.name}</h2><strong>{money(receipt.amount)}</strong><p>{receipt.cancel_reason?'Versement annulé':'Reste à payer : '+money(balance(receiptStudent))}</p></div><details className="receipt-fold"><summary>Voir le reçu complet</summary><article className="receipt"><div className="receipt-header"><h2>{data.settings.name}</h2><p>{data.settings.address} {data.settings.phone}</p></div><div className="receipt-title">REÇU DE SCOLARITÉ{receipt.cancel_reason&&' · ANNULÉ'}</div><p className="receipt-number">{receipt.receipt_number?'SR-'+String(receipt.receipt_number).padStart(6,'0'):'SR-'+receipt.id.toUpperCase()}</p><div className="balance"><span>Élève</span><b>{receiptStudent.name}</b></div><div className="balance"><span>Classe</span><b>{receiptStudent.class_name} · {receiptStudent.year}</b></div><div className="balance"><span>Date</span><b>{displayDate(receipt.date)}</b></div><div className="receipt-amount"><span>Montant reçu</span><strong>{money(receipt.amount)}</strong></div><div className="balance"><span>Paiement</span><b>{receipt.method}</b></div>{receipt.created_by&&<div className="balance"><span>Enregistré par</span><b>{receipt.created_by}</b></div>}{receipt.reference&&<div className="balance"><span>Référence</span><b>{receipt.reference}</b></div>}<div className="balance"><span>Reste à payer à ce jour</span><b>{money(balance(receiptStudent))}</b></div>{receipt.cancel_reason&&<p>Motif : {receipt.cancel_reason}</p>}<div className="signatures"><span>Signature de la caisse</span><span>Cachet de l’école</span></div></article></details><button className="primary full print-button" onClick={close}>Terminé</button><button className="secondary full print-button" onClick={async()=>{const text=data.settings.name+' · '+(receipt.receipt_number?'SR-'+String(receipt.receipt_number).padStart(6,'0'):'SR-'+receipt.id)+'\n'+receiptStudent.name+' · '+receiptStudent.class_name+'\n'+(receipt.cancel_reason?'REÇU ANNULÉ · ':'')+'Paiement : '+money(receipt.amount)+' · '+displayDate(receipt.date)+'\nReste à payer à ce jour : '+money(balance(receiptStudent));try{if(navigator.share)await navigator.share({title:'Reçu de scolarité',text});else{await navigator.clipboard.writeText(text);setNotice('Reçu copié. Vous pouvez le coller dans un message.');}}catch{}}}>Partager le reçu</button><button className="secondary full print-button" onClick={()=>{const fold=document.querySelector<HTMLDetailsElement>('.receipt-fold');const wasOpen=fold?.open;if(fold)fold.open=true;window.print();if(fold)fold.open=Boolean(wasOpen);}}><Printer size={18}/> Imprimer ou garder en PDF</button></>}
</section></div>}
</div>;
}
